# Form implementation generated from reading ui file
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt

class Ui_MainWindow(object):
    
    # open Settings window
    def open_window(self):
        from Settings import Ui_SettingsWindow
        
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SettingsWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    # remove items from list
    def remove(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        item = self.listWidget.takeItem(row)
        del item
    
    def setupUi(self, MainWindow):
        from PyQt5.QtWidgets import QApplication, QWidget
        
        MainWindow.setObjectName("MainWindow")
        
        # get screen size
        self.desktop = QApplication.desktop()
        self.screenRect = self.desktop.availableGeometry()
        self.screen_height = self.screenRect.height()
        self.screen_width = self.screenRect.width()
        
        MainWindow.resize(self.screen_width, self.screen_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.checkBoxImageOutput = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxImageOutput.setGeometry(QtCore.QRect(self.screen_width*0.835, self.screen_height*0.77,
                                                          self.screen_width*0.105, self.screen_height*0.102))
        self.checkBoxImageOutput.setObjectName("checkBoxImageOutput")
        self.checkBoxImageOutput.setStyleSheet("QCheckBox::indicator"
                                               "{"
                                                   "width :" + str(int(self.screen_width*0.03)) + "px;"
                                                   "height :" + str(int(self.screen_width*0.03)) + "px;"
                                               "}"
                               
                                               "QCheckBox::indicator:checked"
                                               "{"
                                                  "image : url(green-led-on.png);"
                                               "}"
                                               
                                               "QCheckBox::indicator:unchecked"
                                               "{"
                                                  "image : url(led-red-on.png);"
                                               "}")
        
        self.checkBoxSaveImage = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxSaveImage.setGeometry(QtCore.QRect(self.screen_width*0.835, self.screen_height*0.852,
                                                        self.screen_width*0.105, self.screen_height*0.102))
        self.checkBoxSaveImage.setObjectName("checkBoxSaveImage")
        self.checkBoxSaveImage.setStyleSheet("QCheckBox::indicator"
                                               "{"
                                                   "width :" + str(int(self.screen_width*0.03)) + "px;"
                                                   "height :" + str(int(self.screen_width*0.03)) + "px;"
                                               "}"
                               
                                               "QCheckBox::indicator:checked"
                                               "{"
                                                  "image : url(green-led-on.png);"
                                               "}"
                                               "QCheckBox::indicator:unchecked"
                                               "{"
                                                  "image : url(led-red-on.png);"
                                               "}")
        
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(self.screen_width*0.013, self.screen_height*0.857,
                                                   self.screen_width*0.105, self.screen_height*0.061))
        self.Start_Button.setObjectName("Start_Button")
        self.Start_Button.setFont(Qt.QFont("MS Shell Dlg 2", 11))
        
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setGeometry(QtCore.QRect(self.screen_width*0.125, self.screen_height*0.857,
                                                  self.screen_width*0.105, self.screen_height*0.061))
        self.Stop_Button.setObjectName("Stop_Button")
        self.Stop_Button.setFont(Qt.QFont("MS Shell Dlg 2", 11))
        
        self.Pattern_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Pattern_Button.setGeometry(QtCore.QRect(self.screen_width*0.303, self.screen_height*0.857,
                                                     self.screen_width*0.105, self.screen_height*0.061))
        self.Pattern_Button.setObjectName("Pattern_Button")
        self.Pattern_Button.setFont(Qt.QFont("MS Shell Dlg 2", 11))
        
        self.Settings_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Settings_Button.setGeometry(QtCore.QRect(self.screen_width*0.830, self.screen_height*0.571,
                                                      self.screen_width*0.105, self.screen_height*0.061))
        self.Settings_Button.setObjectName("Settings_Button")
        self.Settings_Button.setFont(Qt.QFont("MS Shell Dlg 2", 11))
        self.Settings_Button.clicked.connect(self.open_window)

        self.Add_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Add_Button.setGeometry(QtCore.QRect(self.screen_width*0.932, self.screen_height*0.163,
                                                 self.screen_height*0.037, self.screen_height*0.037))
        self.Add_Button.setText("")
        self.Add_Button.setObjectName("Add_Button")
        self.Add_Button.setObjectName("pushButton_2")
        self.Add_Button.setStyleSheet("QPushButton{border-image: url(plus.png)}"
                                      "QPushButton::pressed{background-color : lightblue;}")
        
        self.Remove_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_Button.setGeometry(QtCore.QRect(self.screen_width*0.932, self.screen_height*0.245,
                                                    self.screen_height*0.037, self.screen_height*0.037))
        self.Remove_Button.setText("")
        self.Remove_Button.setObjectName("Remove_Button")
        self.Remove_Button.setStyleSheet("QPushButton{border-image: url(remove.png)}"
                                         "QPushButton::pressed{background-color : lightblue;}")
        self.Remove_Button.clicked.connect(self.remove)
        
        self.Edit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Edit_Button.setGeometry(QtCore.QRect(self.screen_width*0.932, self.screen_height*0.204,
                                                  self.screen_height*0.037, self.screen_height*0.037))
        self.Edit_Button.setText("")
        self.Edit_Button.setObjectName("Edit_Button")
        self.Edit_Button.setStyleSheet("QPushButton{border-image: url(edit.png)}"
                                       "QPushButton::pressed{background-color : lightblue;}")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(self.screen_width*0.84, self.screen_height*0.122,
                                            self.screen_width*0.115, self.screen_height*0.043))
        self.label.setObjectName("label")
        #self.label.setFont(Qt.QFont("MS Shell Dlg 2", 11))
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(self.screen_width*0.831, self.screen_height*0.163,
                                                 self.screen_width*0.1, self.screen_height*0.35))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        
        self.frame = QtWidgets.QLabel(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(self.screen_width*0.013, self.screen_height*0.025,
                                            self.screen_width*0.789, self.screen_height*0.816))
        self.frame.setObjectName("frame")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, self.screen_width*0.611, self.screen_height*0.037))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Calibration"))
        self.checkBoxImageOutput.setText(_translate("MainWindow", "Image Output"))
        self.checkBoxSaveImage.setText(_translate("MainWindow", "Save Image"))
        self.Start_Button.setText(_translate("MainWindow", "START"))
        self.Stop_Button.setText(_translate("MainWindow", "STOP"))
        self.Pattern_Button.setText(_translate("MainWindow", "Pattern"))
        self.Settings_Button.setText(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Image Width & Height"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        
        # set default item with 0-index
        self.listWidget.setCurrentItem(self.listWidget.item(0))

        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "640x480"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "800x600"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "1024x768"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "1920x1080"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())