# Form implementation generated from reading ui file
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsWindow(object):
    
    # set value to text label from the slider
    def change_value(self):
        size = self.horizontalSlider.value()
        self.slider_label.setText(str(size))
    
    def close_settings_window(self):
        self.SettingsWindow.close()
        
    def setupUi(self, SettingsWindow):
        from PyQt5.QtWidgets import QApplication, QWidget
        
        #for close_settings_window function
        self.SettingsWindow = SettingsWindow
        
        SettingsWindow.setObjectName("SettingsWindow")
        
        #get screen size
        self.desktop = QApplication.desktop()
        self.screenRect = self.desktop.availableGeometry()
        self.screen_height = self.screenRect.height()*0.322
        self.screen_width = self.screenRect.width()*0.232
        
        SettingsWindow.resize(self.screen_width, self.screen_height)
        
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gain_label = QtWidgets.QLabel(self.centralwidget)
        self.gain_label.setGeometry(QtCore.QRect(self.screen_width*0.09, self.screen_height*0.119, 
                                            self.screen_width*0.229, self.screen_height*0.095))
        self.gain_label.setObjectName("gain_label")
        
        self.squareSize_label = QtWidgets.QLabel(self.centralwidget)
        self.squareSize_label.setGeometry(QtCore.QRect(self.screen_width*0.09, self.screen_height*0.298,
                                              self.screen_width*0.381, self.screen_height*0.095))
        self.squareSize_label.setObjectName("squareSize_label")
        
        self.squareSize = QtWidgets.QLineEdit(self.centralwidget)
        self.squareSize.setGeometry(QtCore.QRect(self.screen_width*0.493, self.screen_height*0.298,
                                                 self.screen_width*0.09, self.screen_height*0.089))
        self.squareSize.setObjectName("squareSize")
        
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(self.screen_width*0.224, self.screen_height*0.149,
                                                       self.screen_width*0.493, self.screen_height*0.06))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setRange(0, 18)
        self.horizontalSlider.valueChanged.connect(self.change_value)
        
        self.slider_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_label.setGeometry(QtCore.QRect(self.screen_width*0.807, self.screen_height*0.119, 
                                                   self.screen_width*0.229, self.screen_height*0.095))
        self.slider_label.setObjectName("slider_label")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(self.screen_width*0.717, self.screen_height*0.655,
                                                       self.screen_width*0.251, self.screen_height*0.119))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.Ok_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Ok_Button.setObjectName("Ok_Button")
        self.Ok_Button.setSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addWidget(self.Ok_Button, 0, 0, 1, 1)
        self.Ok_Button.clicked.connect(self.close_settings_window)
        
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 223, 18))
        self.menubar.setObjectName("menubar")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.gain_label.setText(_translate("SettingsWindow", "Gain"))
        self.squareSize_label.setText(_translate("SettingsWindow", "Chessboard square size"))
        self.squareSize.setText(_translate("SettingsWindow", ""))
        self.slider_label.setText(_translate("SettingsWindow", "0"))
        self.Ok_Button.setText(_translate("SettingsWindow", "OK"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
